### ISSUE TITLE
Error trying to install packages

### ISSUE THREAD

**Issue by pankajkumar229** [Anaconda-Platform/nb_conda#44]
On the UI, when I try to install a package, I get a forbidden error. 

On the notebook, I get the following errors:

notebook stderr: [E 04:45:33.756 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/mnt/nfs/pankajk81@gmail.com/conda_env/envs/jon1/lib/python2.7/site-packages/notebook/base/handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/mnt/nfs/pankajk81@gmail.com/conda_env/envs/jon1/lib/python2.7/site-packages/nb_conda/handlers.py", line 62, in get
        self.finish(json.dumps(self.env_manager.env_packages(env)))
      File "/mnt/nfs/pankajk81@gmail.com/conda_env/envs/jon1/lib/python2.7/site-packages/nb_conda/envmanager.py", line 124, in env_packages
        "packages": [pkg_info(package) for package in data]
      File "/mnt/nfs/pankajk81@gmail.com/conda_env/envs/jon1/lib/python2.7/site-packages/nb_conda/envmanager.py", line 16, in pkg_info
        name, version, build = s.rsplit('-', 2)
    AttributeError: 'dict' object has no attribute 'rsplit'
[E 04:45:33.771 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.8", 
      "Accept-Encoding": "gzip, deflate, sdch", 
      "X-Requested-With": "XMLHttpRequest", 
      "Host": "52.41.180.39:32785", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36", 
      "Connection": "keep-alive", 
      "Referer": "http://52.41.180.39:32785/tree", 
      "Cookie": "_xsrf=2|a0fa368e|417be503be862d84e898b478c6bb1bed|1487733014; username-52-41-180-39-32787=\"2|1:0|10:1487733019|27:username-52-41-180-39-32787|44:OWI4YjQ0Y2Q4Zjk5NDI5NmEyNmZmY2ZlN2JkNjZiMTY=|cd5fd4840f71f946faf1e872391f041fcdafb30ba2fe7ee4699801131fda8db0\"; username-52-41-180-39-32786=\"2|1:0|10:1487733757|27:username-52-41-180-39-32786|44:N2ZlNDBjMzBiODk1NDczNThiYTFjOGIzZjdlYzJmZDY=|994244f06596fe195db2950a3e0cc1eaf07116a0656e0c03720ec33df74f55ad\"; username-52-41-180-39-32785=\"2|1:0|10:1487738258|27:username-52-41-180-39-32785|44:OWZlZWU0MDY0ZTZlNDcyYmEwZWE3NjFjNzkxMzM0YTE=|2785cd2f1bd0098ffbc2bf18109d89f0407458b1650c857cfe25521995040630\"; connect.sid=s%3Am1PhgXtpdgDnwYO1DPf71NkVgwBNWkUO.DIr8YCshPx0SiRfv3FMiOTlJWVcrvkBYYvO8nkVTgIA"
    }
[E 04:45:33.771 NotebookApp] 500 GET /conda/environments/jon1?_=1487738714673 (70.213.8.242) 9129.27ms referer=http://52.41.180.39:32785/tree

HeartBeat 2017-02-22T04:45:41.279Z SEssion cA2ebFim2XTf9mXzssmlrSq6xtko7Ptn
HeartBeat 2017-02-22T04:45:48.384Z SEssion m1PhgXtpdgDnwYO1DPf71NkVgwBNWkUO
HeartBeat 2017-02-22T04:45:58.755Z SEssion cA2ebFim2XTf9mXzssmlrSq6xtko7Ptn
HeartBeat 2017-02-22T04:46:11.289Z SEssion cA2ebFim2XTf9mXzssmlrSq6xtko7Ptn
HeartBeat 2017-02-22T04:46:18.394Z SEssion m1PhgXtpdgDnwYO1DPf71NkVgwBNWkUO
notebook stderr: [W 04:46:21.143 NotebookApp] 403 POST /conda/environments/jon1/packages/install (70.213.8.242): '_xsrf' argument missing from POST

notebook stderr: [W 04:46:21.156 NotebookApp] 403 POST /conda/environments/jon1/packages/install (70.213.8.242) 12.86ms referer=http://52.41.180.39:32785/tree

**Comment by damianavila** [comment]
>403 POST /conda/environments/jon1/packages/install (70.213.8.242): '_xsrf' argument missing from POST

Seems to be the issue, which `notebook` version are you using?

**Comment by pankajkumar229** [comment]
Thanks! Just upgraded and the error went away

**Comment by StudioEtrange** [comment]
Hello
I got the same problem
What did you update exactly ?

**Comment by CorneelDragon** [comment]
I got the same error and update didn't fix it :(

**Comment by pankajkumar229** [comment]
I tested again. I somehow missed the error last time. It is still there.

**Comment by StudioEtrange** [comment]
For now, if I want jupyter contrib nb extensions and nb conda extension, I had to fix some specific versions : 

```
conda install nb_conda
conda install --yes -c conda-forge jupyter_contrib_nbextensions
conda install --yes jupyter=1.0.0 notebook=4.2.3
pip install git+https://github.com/kalefranz/nb_conda.git@d1e5eb8fcabfa6e5404bbce3ba5dec5456353618 --upgrade"
```

Because dependencies are a bit messed up, and some fixes in kalefranz are in official package

**Comment by damianavila** [comment]
Reopening, there seems to be some issues with the _xsrf.

**Comment by damianavila** [comment]
This is solved in master by #43 and #48. Closing now.

**Comment by CorneelDragon** [comment]
@damianavila Do you care to share how it is actually solved? I updated conda but the problem persists.

**Comment by damianavila** [comment]
@CorneelDragon this is fixed in master (tagged 2.2.0) but not released yet... in fact I am building the release in conda-forge right now, but the queue is long yet... I guess the 2.2.0 version representing the current master will be available in the next few hours...

**Comment by CorneelDragon** [comment]
@damianavila  When / how can I update to this 2.2.0? If I update nb_conda or uninstall and install it I remain on 2.0.0

**Comment by damianavila** [comment]
@CorneelDragon you need to install it from conda-forge for now: `conda install -c conda-forge nb_conda` should get you the latest version.
